name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      pnpm_cache_dir: ${{ steps.pnpm-cache.outputs.STORE_PATH }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public'

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public'

      - name: Prettier check
        run: pnpm format:check

      - name: Lint check
        run: pnpm lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public'

      - name: Run tests
        run: pnpm test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: npx prisma generate
        env:
          DATABASE_URL: 'postgresql://johndoe:randompassword@localhost:5432/mydb?schema=public'

      - name: Build project
        run: pnpm build
